export const SAVE_DATA='SAVE_DATA'; //to save signup data
export const AUTH_DATA='AUTH_DATA'; //for authentication of data
export const USER_FETCH_SUCCEEDED='USER_FETCH_SUCCEEDED'; //when response is obtained fron database
export const USER_FETCH_FAILED='USER_FETCH_FAILED';//when response is not obtained fron database
export const INPUT_SCREEN='INPUT_SCREEN';//for the calculation 
export const SAVE_HISTORY='SAVE_HISTORY';//to save calculation history
export const GET_HISTORY='GET_HISTORY';//to obtain the calculation history from database
export const HISTORY_FETCH_SUCCEEDED='HISTORY_FETCH_SUCCEEDED';//when history is successfully obtained
export const HISTORY_FETCH_FAILED='HISTORY_FETCH_FAILED';//when history cannot be retrieved successfully 
export const DATA_SAVE_SUCCEEDED='DATA_SAVE_SUCCEEDED';//when user data is saved in the database
export const DATA_SAVE_FAILED='DATA_SAVE_FAILED';//when user data is failed to save in the database