export const SAVE_DATA='SAVE_DATA';
export const AUTH_DATA='AUTH_DATA';
export const USER_FETCH_SUCCEEDED='USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED='USER_FETCH_FAILED';
export const INPUT_SCREEN='INPUT_SCREEN';
export const SAVE_HISTORY='SAVE_HISTORY';
export const GET_HISTORY='GET_HISTORY';
export const HISTORY_FETCH_SUCCEEDED='HISTORY_FETCH_SUCCEEDED';
export const HISTORY_FETCH_FAILED='HISTORY_FETCH_FAILED';

