export const SAVE_DATA='SAVE_DATA';
export const AUTH_DATA='AUTH_DATA';
export const USER_FETCH_SUCCEEDED='USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED='USER_FETCH_FAILED';
export const EVALUATE_EXPRESSION='EVALUATE_EXPRESSION';
export const INPUT_SCREEN='INPUT_SCREEN';
export const CLEAR_RESULT = "CLEAR_RESULT";
